apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
  namespace: jf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - image: quay.io/minio/minio:latest
        name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: root
        - name: MINIO_SECRET_KEY
          value: admin@cloud
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        command:
        - /bin/bash
        - -c
        args:
        - export MINIO_SERVER_URL=http://${NODE_IP}:30002 && minio server /data --console-address :9090 --address :30002
        volumeMounts:
        - mountPath: /data
          name: localvolume
        - mountPath: /root/.minio
          name: configdata
      volumes:
      - name: localvolume
        hostPath: # MinIO generally recommends using locally-attached volumes
          path: /home/guozijing/minio/data # Specify a path to a local drive or volume on the Kubernetes worker node
          type: DirectoryOrCreate
      - name: configdata
        hostPath:
          path: /home/guozijing/minio/config

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: minio
  name: minio
  namespace: jf
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30001
    name: console
  - port: 30002
    protocol: TCP
    targetPort: 30002
    name: control
    nodePort: 30002
  type: NodePort
  selector:
    app: minio
